=== Skitak/portfolio-Veronique/Atelier 3/xml/librairie.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="librairie" type="typeLibrairie"/>

	<xs:complexType name="typeLibrairie">
		<xs:sequence>
			<xs:element name="jeu" type="typeJeu" minOccurs="4" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeJeu">
		<xs:sequence>
			<xs:element name="titre" type="xs:string" />
			<xs:element name="genre" type="xs:string" />
			<xs:element name="editeur" type="xs:string" />
			<xs:element name="parution" type="xs:date" />
			<xs:element name="note" type="typeNote" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="joueurs" type="xs:positiveInteger" />
			<xs:element name="age" type="xs:positiveInteger" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeNote">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="magazine" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== Skitak/portfolio-Veronique/Atelier 3/xml/librairie.xml
<?xml version="1.0" encoding="UTF-8" ?>
<librairie
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="librairie.xsd" >
	<jeu>
		<titre>overwatch</titre>
		<genre>fps</genre>
		<editeur>blizzard</editeur>
		<parution>2016-02-10</parution>
		<note magazine="jeuxvideos.com">16</note>
		<joueurs>30000000</joueurs>
	</jeu>

	<jeu>
		<titre>the last of us</titre>
		<genre>action aventure survival</genre>
		<editeur>sony</editeur>
		<parution>2013-11-10</parution>
		<note magazine="steam">18</note>
		<joueurs>6000000</joueurs>
		<age>18</age>
	</jeu>

	<jeu>
		<titre>hyper light drifter</titre>
		<genre>action aventure</genre>
		<editeur>heart machine</editeur>
		<parution>2016-06-13</parution>
		<note magazine="steam">18</note>
		<note magazine="gamasutra">19</note>
		<joueurs>600000</joueurs>
	</jeu>

	<jeu>
		<titre>league of legends</titre>
		<genre>moba</genre>
		<editeur>tencent</editeur>
		<parution>2009-03-27</parution>
		<note magazine="TIGsource">16</note>
		<joueurs>100000000</joueurs>
	</jeu>

</librairie>
